# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b20469ccf38209b4b25185bf0d29e2391a01ab83baaf2c58b8fe56aa38d3f84c50f3ed4fa48f93a1578717eb424f8a384d21d94674bbe0955960e5a2fa78fee9

test:
  secret_key_base: 5a4b9cd17e20d12bcef5a7b9e3a2a0633b98b75d1a10602a2115ff1e847d54e6016f44a091fb967d41e33e5514fca0d9e3909c7d317fc315ff735e6a4630efd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
